[package]
name = "smtp-message"
version = "0.1.0"
authors = ["LÃ©o Gaspard <leo@gaspard.io>"]
license = "MIT"
categories = ["email", "network-programming", "parser-implementations"]
keywords = ["parser", "builder", "smtp", "email"]
description = "Line-oriented parser and builder for SMTP protocol messages"

[dependencies]
bytes = "0.4.6"
nom = "3.2"
failure = "0.1.1"
failure_derive = "0.1.1"
tokio = "0.1.5"

[dev-dependencies]
quickcheck = "0.6.2"
